version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: flight_managment_system
    volumes:
      - ./mongo-data:/data/db  # Persist MongoDB data
      - ./mongo-config:/data/configdb  # Config volume

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"  # Expose Mongo-Express on localhost
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    volumes:
      - ./mongo-express-data:/data/db  # Persist Mongo-Express data (if needed)

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"  # Expose Zookeeper on localhost
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper  # Persist Zookeeper data

  redis-db:
    container_name: redis-db
    command: valkey-server /usr/local/etc/valkey/valkey.conf --save 60 1 --loglevel warning
    image: valkey/valkey:7.2
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./valkey/valkey-data:/data
      - ./valkey/users_acl:/etc/valkey
      - ./valkey/valkey_conf:/usr/local/etc/valkey

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:${KAFKA_INTERNAL_PORT},OUTSIDE://${KAFKA_HOST}:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENERS: INTERNAL://kafka:${KAFKA_INTERNAL_PORT},OUTSIDE://0.0.0.0:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - ./kafka-data:/var/lib/kafka/data  # Persist Kafka data

volumes:
  mongo-data:
  mongo-config:
  mongo-express-data:
  zookeeper-data:
  kafka-data:
